name: Approve Sync to Integration 🚀
on: 
  pull_request_target:
    branches:
      - 'int/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if:  startsWith(github.event.pull_request.head.ref, 'sync/')
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Ready to sync 🚀"
